CC = arm-linux-gnueabi-gcc
CFLAGS = -Wall

TARGET = wifi_receiver
SRCS = wifi_receiver.c
OBJS = $(SRCS:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)
